### ISSUE TITLE
Configurable file name pattern

### ISSUE THREAD

**Issue by Accelsnow** [chfourie/obsidian-journal-folder#2]
Hi I recently found out about this plugin and think that the journal header looks fantastic and would be a great feature for daily note management. However, I currently have many notes and the files are named differently. I am wondering if configurable filename pattern would be an upcoming feature? Thanks!

**Comment by chfourie** [comment]
Good day @Accelsnow.  I would like to implement configurable file name patterns as a feature somewhere in the future.  However, there are a lot of other features that has higher priority.  I do not expect this to be implemented in 2024.
