### ISSUE TITLE
Recursive journal folder

### ISSUE THREAD

**Issue by Accelsnow** [chfourie/obsidian-journal-folder#3]
Hi I recently found out about this plugin and think that the journal header looks fantastic and would be a great feature for daily note management. I currently manage my daily notes in a hierarchical folder structure in `YY/YY-MM/YY-MM-DD` format, where the yearly notes and monthly notes are essentially the folder notes (using this plugin [FolderNote](https://github.com/LostPaul/obsidian-folder-notes)). Screenshot:
![image](https://github.com/user-attachments/assets/19c69c86-0703-4a51-9524-e763f5be1fc1)

So basically the yearly note for 2015 is `diary/15/15.md`, which is the folder note for folder `diary/15`. Similarly, the monthly note for 2015-06 is `diary/15/15-06/15-06.md`, which is the folder note for folder `diary/15/15-06`. Essentially, although my yearly, monthly and daily notes follow strict filename patterns `YY.md` `YY-MM.md` `YY-MM-DD.md`, they are scattered in a hierarchical folder structure under the `diary` folder.

I think the current journal-folder only searches within the same folder where the note resides. I am wondering if it would be possible to define a "parent folder" field in the journal-header, so that the journal header searches this parent folder's subfolders recursively to display the links? 

Thanks!

**Comment by chfourie** [comment]
Good day @Accelsnow.   It has been a design decision up front to specifically keep all notes in the same folder.  I am not planning on supporting hierarchical folder structures in the foreseeable future.
