### ISSUE TITLE
Please provide a beginners step by step tutorial for the journal folder plugin

### ISSUE THREAD

**Issue by wechsler42** [chfourie/obsidian-journal-folder#5]
Hi there,
thanks for providing us the journal folder plugin.
May I ask for a short beginners tutorial which leads to a working example? I spent now now more than 2 hours to get the plugin working. Unfortunately, without success.  Perhaps it is written somewhere but I must say, I am overwhelmed about all the configuration options on vault, folder, etc. level.

**Comment by chfourie** [comment]
Good day @wechsler42 .  To begin using the plugin, follow the following steps:

**Step 1**
Create a new folder somewhere in your vault.  For this example I will use the folder "/Journal".

**Step 2**
Create a file with today's date in the format "yyyy-mm-dd" as name.  E.g. "/Journal/2024-09-23.md"

**Step3** 
Add the following to the top of the file you created (note that the first line is optional)...

<img width="683" alt="image" src="https://github.com/user-attachments/assets/9f51fd04-8edc-47e6-98b5-a650f3ba2844">

Thats it.  you will notice that if you either move your cursor out of the code block or switch to reading view, the note will now display a header similar to the following...

<img width="726" alt="image" src="https://github.com/user-attachments/assets/7cfbd59c-5bd3-4d92-9f4a-20c72fee85bc">

To making the setting up of subsequent journal pages more seamless, I suggest either making use of the built-in templating functionality or of the Templater plugin available in the community plugin store.
